export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_QUANTITY_OF_PRODUCT = "INCREASE_QUANTITY_OF_PRODUCT";
export const DECREASE_QUANTITY_OF_PRODUCT = "DECREASE_QUANTITY_OF_PRODUCT";
