export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORIES_LOADING = "SET_CATEGORIES_LOADING";
export const SET_CATEGORIES_ERROR = "SET_CATEGORIES_ERROR";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_CURRENCY_LOADING = "SET_CURRENCY_LOADING";
export const SET_CURRENCY_LOADING_ERROR = "SET_CURRENCY_LOADING_ERROR";
