export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const FETCH_PRODUCT_LOADING = "FETCH_PRODUCT_LOADING";
export const SELECT_ACTIVE_PRODUCT_ATTRIBUTE =
  "SELECT_ACTIVE_PRODUCT_ATTRIBUTE";
